name: JS Doc README and gh-pages
on:
  push:
    branches:
      - master
jobs:
  job0:
    name: Update Readme
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Build Assets
        run: npm build
      - name: Test
        run: npm test
      - name: update Readme
        run: npm updatereadme
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update Readme" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}